version: "3"
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports: 
      - "5000:5000"
    image: mahirlabibdihan/bitsunplugged-dev
    container_name: bitsunplugged-fullstack-dev
    env_file:
      - backend/.env.production