name: API Tests

on:
  push:
    branches:
      - dihan

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: cd backend && npm install
    
    - name: Build and start the backend
      run: |
        npm start &
        sleep 10      

  test:
    needs: backend
    runs-on: ubuntu-latest

    env:
      POSTMAN_COLLECTION_PATH: '/etc/newman/Bits Unplugged.postman_collection.json'
      BASE_URL: 'http://localhost:5000'  # Update with your API's base URL

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Postman tests
      run: |
        docker run \
          -e BASE_URL=${BASE_URL} \
          -v ${{ github.workspace }}:/etc/newman \
          postman/newman:alpine \
          run /etc/newman/"Bits Unplugged.postman_collection.json"