name: DevTest

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: kuddusmia
      DB_USER: postgres.mnqhazjbbmyvpwbzjfoi
      DB_PASS: "#include<D1h@n.h>"
      DB_HOST: aws-0-us-east-1.pooler.supabase.com
      DB_PORT: 5432
      DB_DB: bitsunplugged
      PORT: 5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd backend && npm ci
        env:
          DB_USER: env.DB_USER
          DB_HOST: env.DB_HOST_DEV
          DB_DB: env.DB_DB
          DB_PASS: secrets.DB_PASS
          DB_PORT: env.DB_PORT
          JWT_SECRET: secrets.JWT_SECRET
          ADMIN_PASS: secrets.ADMIN_PASS

      - name: Run tests
        run: cd backend && npm run test
