name: DevDeploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Install dependencies
        run: sudo apt install docker-compose
          
      - name: Build the Docker image
        run: docker-compose -f docker-compose.dev.yml build
      
      - name: Push to Docker Hub
        run: docker push mahirlabibdihan/bitsunplugged-dev:latest
      
      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/deploy/srv-clhk93ebbf9s73b1o490?key=775Phjnzh2w"
