name: PingTest

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: sudo apt install docker-compose
        
      - name: Build image
        run: docker-compose -f docker-compose.dev.yml build

      - name: Run tests
        run: docker run -e CI=true --env-file backend/.env.production mahirlabibdihan/bitsunplugged-backend npm run test
