name: ProdDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install dependencies
        run: sudo apt install docker-compose

      - name: Build the Docker image
        run: docker-compose -f docker-compose.prod.yml build
        env:
          DB_USER: env.DB_USER
          DB_HOST: env.DB_HOST_PROD
          DB_DB: env.DB_DB
          DB_PASS: secrets.DB_PASS
          DB_PORT: env.DB_PORT
          JWT_SECRET: secrets.JWT_SECRET
          ADMIN_PASS: secrets.ADMIN_PASS

      - name: Push to Docker Hub
        run: docker push mahirlabibdihan/bitsunplugged-app:latest

      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/deploy/srv-cl69io2uuipc73c9oq7g?key=iuS9vv2z5d0"
