name: ProdTest

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install docker-compose

      - name: Build the Docker image
        run: docker build -t mahirlabibdihan/bitsunplugged-app . --build-arg arg=prod
        
      - name: Run tests
        run: |
          docker run \
          -e CI=true \
          -e DB_USER=${{ vars.DB_USER_PROD }} \
          -e DB_HOST=${{ vars.DB_HOST_PROD }} \
          -e DB_DB=${{ vars.DB_DB }} \
          -e "DB_PASS=${{ secrets.DB_PASS }}" \
          -e DB_PORT=${{ vars.DB_PORT }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e ADMIN_PASS=${{ secrets.ADMIN_PASS }} \
          mahirlabibdihan/bitsunplugged-app npm run test
